### PR TITLE
UX improvements

### PR DESCRIPTION
**Pull request by DPS2004**
- Adds a Settings menu accessible from the pause screen.
- Adds [more options for the main menu, including layout and color](https://streamable.com/t8cph7)
- Adds [3D Banner to 3DS build](https://streamable.com/ph18ze)
- Adds support for built in carts (referred to as pack-ins) on 3DS and Windows. Disabled by default in the Makefile
- Adds makefile for SDL2 on Windows (for development purposes)

### CODE REVIEW

**Review by jtothebell — CHANGES_REQUESTED** [review]
I had a look through this today, and while there is some good stuff in here, I can't merge it as is. 

The biggest thing is the presence of the Pico-8 logo in the banner and the NoLabel label graphic. The Pico-8 FAQ (https://www.lexaloffle.com/pico-8.php?page=faq) clearly says this shouldn't be used in other software unless Zep says, and honestly, I don't think I want to ask, because I don't want this project to be confused with official Pico-8.

With that being a deal breaker for this PR as is, its probably worth mentioning that it would be preferable to have a single PR per feature, and there are several features here. If I could verify that they're all working well, I would still merge it, but as is a problem with one feature prevents the whole thing from getting merged.

Other changes that need to happen:

- The resize hotkey and menu settings should default to their previous settings. I thought screen resizing was broken at first, and the menu took long enough to load that I thought the app was frozen. Maybe if there was a loading indicator or something then the menu could default to the fancy menu.
- The stretch option text in the menu doesn't match what it changes the stretch to
- there is a small visual artifact under the FAKE-08 title in the old menu
- Is there a reason both carts.zip and cartzip.h are checked in? Although it would be preferable to inlude the carts.zip file in romfs on 3ds, I recognize its easier to include the bytes in the header
- you have a TODO for vita that mentions carts shouldn't get unzipped every time the app starts, and I agree, that needs to be addressed

**Comment by DPS2004** [comment]
Hi, thank you for the detailed response.

- Splitting this up into smaller commits will be hard, because the options cart and the menu cart are somewhat built on top of each other. In the future, though, I will try to be more careful about not shoving things into one branch during development.
- Since the Pico-8 logo can't be used for the banner and the no label image, I think it is safe to assume that the sprites from Jelpi should not be used either in the banner. So for now, I will revert back to the 2D banner.
- I will change the default value for the resize hotkey to be enabled, and I will try to add a loading indicator to the fancy menu.
- carts.zip being included was not on purpose, and I chose to use a header instead of romfs (or equivalent for other platforms) because that would require a *lot* of platform specific code.
- the cart unzipping only once thing is a pretty easy fix, same with the classic menu artifact.

I will try to get these changes done over the weekend.

**Comment by jtothebell** [comment]
Sounds good, thanks.  No rush, of course, I appreciate your work. This also made me think I should probably put together PR and other community guidelines. Unfortunately, since you're the first significant feature contributor, I'm figuring that out as I go.

**Comment by DPS2004** [comment]
(closing for now while i reorganize into multiple PRs)

**Pull request closed without merging**
